// _________________________________________________________
// find all multiples of 3 and 5 below 1000 and add the sum

var sum = 0;
for (var i = 0; i < 10; i++) {
  if (i % 3 === 0 || i % 5 === 0) {
    sum += i;
  }
}
console.log('Sum: %d', sum);

// _________________________________________________________

// Each new term in the Fibonacci sequence is generated by adding the previous two
// terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed
// 1000, return the even numbers
// 1) create an array of a Fibonacci sequcen from 1 - 1000
function fibSeq(max) {
  var fib = [1, 2];
  for(var i=fib.length; i<max; i++) {
    fib[i] = fib[i-2] + fib[i-1];
  }
  console.log(fib);
}

fibSeq(1000);




// _________________________________________________________
// _________________________________________________________
